### ISSUE TITLE
Add enpoints for pipeline related tasks

### ISSUE THREAD

**Issue by Alopalao** [kytos-ng/of_multi_table#2]
Add the next endpoints.
- GET `/api/kytos/of_multi_table/v1/pipeline` - Get all pipelines in the database. Parameters enabled and disabled are allowed.
- GET `/api/kytos/of_multi_table/v1/pipeline/<pipeline_id>` - Get a single pipeline that matches the given pipeline id.
- POST `/api/kytos/of_multi_table/v1/pipeline/<pipeline_id>/enable` - Enable pipeline to be applied to all switches
- POST `/api/kytos/of_multi_table/v1/pipeline/<pipeline_id>/disable` - Disable pipeline in case of the user wants to return to the default set up.
- POST `/api/kytos/of_multi_table/v1/pipeline` - Add pipeline to database. Its body is similar to "pipeline.multi_table".
- DELETE `/api/kytos/of_multi_table/v1/pipeline/<pipeline_id>` - Delete only disabled pipeline from database otherwise it should prompt the user to disable the pipeline first.

**Comment by viniarck** [comment]
Nice @Alopalao. 

Could you also set the GH labels `epic_openflow_multi_table` and `2023.1` on this issue and on related ones that you'll open just so it shows up on our GitHub filters and Kanban board?
