### ISSUE TITLE
Include `kytos/of_multi_table` on Test Analytics Dashboard

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/of_multi_table#23]
Same as https://github.com/kytos-ng/kytos_stats/issues/2, except it's for including `kytos/of_multi_table` on [Test Analytics Dashboard](https://kytos-tests.amlight.net/index.html)

@Alopalao, if you could add this to your radar for `2023.1` too, it's a simple task, but still it'd be nice to have it in the dashboard since it'll be mentioned in the upcoming release notes. 

In order to include it in the dashboard, you need to include it on https://gitlab.ampath.net/kytos/test-panel-api, in summary, it fetches the coverage stats from scrutinizer via an API and exposes it to the dashboard front-end, but the repo link needs to be included on `app.py`. @italovalcy can also further clarify how to do it.

**Comment by Alopalao** [comment]
Added, [merged request](https://gitlab.ampath.net/kytos/test-panel-api/-/merge_requests/1/diffs)

**Comment by viniarck** [comment]
The change looks good @Alopalao, once the Dashbord is also generating correctly the links in the front-end this can get closed. I've just opened a new thread with you and Italo regarding a 502 error. It's great that also `kytos-ng/kytos_stats` got included too cc'ing @gretelliz

**Comment by italovalcy** [comment]
@viniarck and @Alopalao the front-end is displaying the results correctly now, after some interventions.
