### ISSUE TITLE
Add in scrutinizer to automatically run tests for pull requests

### ISSUE THREAD

**Issue by Ktmi** [kytos-ng/of_multi_table#41]
Currently this repository doesn't have scrutinizer setup to run automatically. Having the ability to run tests automatically for pulls helps make sure that resulting merge will go well.

**Comment by viniarck** [comment]
Good catch, David. 

For some reason, its repo config had some extra config on scrutinizer. I've just updated it to use the global scrutinizer config, it's expected to run from this point forward. I see that it jsut picked up for your PR https://scrutinizer-ci.com/g/kytos-ng/of_multi_table/inspections/9c24807f-32ac-4122-b940-1bdd6197172a. 

Let's leave the issue open, and see if it'll keep behaving correctly from now on.
